### ISSUE TITLE
Find a place on the internet to host yunity.box

### ISSUE THREAD

**Issue by nicksellen** [yunity/yunity-vagrant#3]
This is a base image with most of the yunity stuff setup in it. It speeds up the deployment a lot.

Anywhere on public http (or https) would be suitable.

**Comment by NerdyProjects** [comment]
We have 50gb space at manitu webhosting we can use for that as long as it is not hundreds  of downloads per month. Unfortunately, I cannot give the credentials away. So we have to see how we rebuild/upload that box. Come to me directly and we can upload one this evening :)

**Comment by nicksellen** [comment]
wget http://ada.local/yunity.box :)

**Comment by NerdyProjects** [comment]
Download via http://p12607.ngcobalt20.manitu.net/download.php?file=yunity.box

**Comment by nicksellen** [comment]
Could we maybe add a redirect so http://yunity.org/yunity.box (or something along those lines) will get 302 redirected to that big ugly url?

**Comment by NerdyProjects** [comment]
Our web setup is really not ready/finished right now. You can add that to the trello or request a redirect like project.yunity.org/dev/yunity.box right now. Best would be to wait two weeks until we have a "finalized" dev and project web setup on a root server.
